# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain dependencies for npm (TypeScript project)
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "daily" # Check for updates weekly
    open-pull-requests-limit: 5

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of GitHub Actions workflows
    schedule:
      interval: "daily" # Check for updates weekly
