services:
  postgres:
    image: postgres:17
    container_name: tattoo-studio-db
    restart: always
    ports:
      - 5445:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tattoo-studio
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
