services:
  postgres:
    image: postgres:17
    container_name: tattoo-studio-db
    restart: always
    ports:
      - 5445:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tattoo-studio
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tattoo-studio-web
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgres://neondb_owner:npg_Sd9xJ0hBZMUH@ep-little-star-a55hlkry-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
