#!/bin/sh

# Run npm test script with passWithNoTests flag
npm test -- --passWithNoTests

# Uncomment the line below if you want to restore Docker verification later
# docker-compose -f docker-compose.verify.yml run verify test
