name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and verify
        run: docker build -f Dockerfile.ci .

  deploy:
    needs: verify
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Check deploy hook configuration
        id: check_hook
        run: |
          if [ -n "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}" ]; then
            echo "hook_exists=true" >> $GITHUB_OUTPUT
          else
            echo "hook_exists=false" >> $GITHUB_OUTPUT
            echo "::warning::No VERCEL_DEPLOY_HOOK_URL secret found. Deployment will be skipped."
          fi

      - name: Trigger Vercel deployment
        if: steps.check_hook.outputs.hook_exists == 'true'
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
          echo "Vercel deployment triggered successfully"
